type Route {
  _key: String
  routeName: String
  origin: String
  destination: String
}

type TravelTime {
  _key: String
  route: Route
  travelTime: Float
  createdAt: String
}

type Query {
  travelTimes(routeName: String): [TravelTime]
  routes: [Route]
  route(routeName: String): Route
}
